### ISSUE TITLE
Leftwm latest published release fails to build with Rust > 1.79

### ISSUE THREAD

**Issue by 0323pin** [leftwm/leftwm#1287]
### Describe the bug

Hi,

FYI, see title.
This is because the `time` crate fails with:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /pbulk/work/devel/cargo-outdated/work/vendor/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

The solution is to update `time` to 0.3.36.

### Expected behavior (optional)

NA

### Steps to reproduce (optional)

NA

### Relevant log output (optional)

```text
NA
```

### OS / Distro

Any

### Additional System Information (optional)

```text
NA
```

### LeftWM Check

```text
NA
```

**Comment by 0323pin** [comment]
Anyone that has the required permissions to cut a new release tag?

**Comment by 0323pin** [comment]
@mautamu Thank you <3
