### ISSUE TITLE
Release 0.5.1 does not compile using Rust 1.80

### ISSUE THREAD

**Issue by pondichys** [leftwm/leftwm#1272]
### Describe the bug

It is currently not possible to compile release **0.5.1** of `leftwm` using rust **1.80**.
The problem lies in `time` crate that issues the following error at compile time

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/seb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

If I update the dependencies running `cargo update time` (which updates to 0.3.36), it works fine.

As I'm working on the update of the leftwm package for Void Linux, I have some constraints if I want to push this version into the official Void repository.
- package should be based on a release tag
- it should compile and run using the current stable version of Rust toolchain

Would you please consider create a new release to fix this issue? And also include the patch from December 2023 #1202 that enables compilation on 32 bit systems.

Best regards.

PS: For the record, I also tried to compile main branch using 1.80 and it does not work either. Same error.

### Expected behavior (optional)

leftwm 0.5.1 should compile using current stable rust-toolchain 1.80

### Steps to reproduce (optional)

Clone the leftwm repo and checkout the 0.5.1 tag
Install mandatory dependencies
Install rust toolchain from stable channel (1.80)
Try to compile leftwm using cargo build --> error

### Relevant log output (optional)

```text
error[E0282]: type annotations needed for `Box<_>`
  --> /home/seb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

### OS / Distro

Linux voidvm 6.6.43_1 #1 SMP PREEMPT_DYNAMIC Sun Jul 28 07:18:17 UTC 2024 x86_64 GNU/Linux

### Additional System Information (optional)

```text
Void Linux using glibc
Rust toolchain 1.80 (current stable)
```

### LeftWM Check

```text
No leftwm check possible as I cannot even compile
```
