### PR TITLE
chore(v0.5.2): bump version, dependencies and prepare release for #1287

### LINKED ISSUE #1287: Leftwm latest published release fails to build with Rust > 1.79
### Describe the bug

Hi,

FYI, see title.
This is because the `time` crate fails with:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /pbulk/work/devel/cargo-outdated/work/vendor/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

The solution is to update `time` to 0.3.36.

### Expected behavior (optional)

NA

### Steps to reproduce (optional)

NA

### Relevant log output (optional)

```text
NA
```

### OS / Distro

Any

### Additional System Information (optional)

```text
NA
```

### LeftWM Check

```text
NA
```

### PR DESCRIPTION
**Pull request by mautamu**
# Description

Bumps dependency versions and leftwm versions to +0.0.1 (I did not skip 0.5.1 for the ones where we could...).

Fixes #1287 

## Type of change

- [x] Development change (no change visible to user)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation only update (no change to the factual codebase)
- [x] This change requires a documentation update

## Updated user documentation:

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [x] Ran `make test` locally with no errors or warnings reported
  Note: To fully reproduce CI checks, you will need to run `make test-full-nix`. Usually, this is not necessary.
- [ ] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

**Comment by 0323pin** [comment]
@mautamu I was going to say LGTM but, the CI is failing. Thank you for looking at this.

**Comment by mautamu** [comment]
@0323pin Should be fixed up now!

**Comment by 0323pin** [comment]
@mautamu Awesome ... all tests passed. Do you want me to build on NetBSD? I use a git-HEAD build on Linux and that is working fine.

**Comment by mautamu** [comment]
@0323pin That would be great if you don't mind! Assuming it works on netbsd and there aren't any objections in the next few hours, think we can try merging it and then running the release.

**Comment by 0323pin** [comment]
@mautamu All good 🚀 

2024-10-17-114340_1366x768_scrot

**Review by 0323pin — APPROVED** [review]

**Comment by 0323pin** [comment]
@mautamu Thank you for cutting a new release. [Merged](https://mail-index.netbsd.org/pkgsrc-changes/2024/10/17/msg308920.html) now.

**Comment by mautamu** [comment]
Absolutely, thanks for raising that the build wasn't working @0323pin!
